### ISSUE TITLE
{val}/scene tag missing for Systems

### ISSUE THREAD

**Issue by perijove** [massif-press/cc-lcp-editor#12]
**Describe the bug**
{val}/scene tag appears to be missing in the system editor

**To Reproduce**
1. Create a new lcp
2. Create a new system for the lcp
3. Add a tag
4. Look for the tag {val}/scene

**Expected behavior**
When selecting tags for a system, I expect to see {val}/scene as an option alongside {val}/turn and {val}/round

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: lcp editor 0.1.2

**Comment by jarena3** [comment]
{val}/scene is not currently supported in the base lancer-data, but may be added as a custom tag
