### ISSUE TITLE
Cannot add new Core Bonuses

### ISSUE THREAD

**Issue by Fivemarks** [massif-press/cc-lcp-editor#14]
**Describe the bug**
New Core Bonuses added to an LCP do not appear and are not saved.

**To Reproduce**
1. Create a new LCP
2. Go to Core Bonuses
3. Attempt to add new Core Bonuses
4. new Core Bonuses will stop being added after the first or fourth Core Bonus

**Expected behavior**
New Core Bonuses do not appear.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Firefox
 - Version 93.0 (64-bit)

**Comment by jarena3** [comment]
I haven't been able to reproduce this with an existing or new manufacturer. Can you confirm you're on LCP editor v0.1.2 or later?

**Comment by jarena3** [comment]
Unable to reproduce
