### ISSUE TITLE
Handling for duplicate IDs

### ISSUE THREAD

**Issue by perijove** [massif-press/cc-lcp-editor#18]
**Is your feature request related to a problem? Please describe.**
It is possible to create multiple items with the same ID, which will lead to data handling issues when loaded into compcon. There is no warning to inexperienced LCP creators about this

**Describe the solution you'd like**
Upon the user entering an ID for a new item, check if there is an item with the same ID in the pack. If there is, highlight the cell in red with a tooltip warning about a duplicate ID.

**Describe alternatives you've considered**
Check for a duplicate ID when attempting to save an item. If there is a duplicate, give the user the option to overwrite or cancel the save.

**Comment by jarena3** [comment]
resolved in 0.3
