### ISSUE TITLE
Fields for numbers are translated into strings when exported to JSON/LCP

### ISSUE THREAD

**Issue by Bluhman** [massif-press/cc-lcp-editor#2]
**Describe the bug**
When editing entries for weapons or systems part of licenses, certain fields that are meant to only accept numbers (i.e. License Level, Ranges) get translated into strings. This causes issues when imported into COMP/CON, and can cause various weapon or system entries to fail to appear if a license level is _entered using the keyboard_ instead of when its _increased or decreased with the Spin Button controls._

**To Reproduce**
1. Go to Manufacturers and Licenses and add a new System, Weapon, or Mod.
2. While entering the information, click on the License Level field and _type in_ a number.
3. Export the weapons/system/mods.json component of the LCP & open it in a text editor
4. See that the number entered is in quotes.

**Expected behavior**
Fields such as this should always convert the value to numbers, even when typed in. Otherwise, license components can fail to appear in the appropriate sections when viewing them in the compendium or when choosing licenses in COMP/CON.

**Screenshots**
![image](https://user-images.githubusercontent.com/3156272/139554161-da951293-12f2-42bb-b956-ba9390925186.png)

An added example of "Range" not being parseable from a string causing the entire Mech Weapons compendium to fail to list: 
![image](https://user-images.githubusercontent.com/3156272/139555234-360c4f9c-b799-471a-ab4a-f79a785491ac.png)

**Comment by jarena3** [comment]
Wrote a fix for this one the C/C side. Will close this once that's tested and deployed.

**Comment by jarena3** [comment]
Fixed in C/C
