### ISSUE TITLE
Equipment Effects for Pilot Gear

### ISSUE THREAD

**Issue by GNUtopia** [massif-press/cc-lcp-editor#20]
**Is your feature request related to a problem? Please describe.**
The editor currently has no way to add equipment effects on pilot gear as per the Signature ranged weapons.

**Describe the solution you'd like**
A new field in the pilot gear editor to enter equipment effects.

**Additional context**
The ability to add such effects is present in COMP/CON already, as evidenced by the aforementioned Signature weapons and some manual testing on my part, though it doesn't seem to work for pilot armour or gear (yet, hopefully).

**Comment by jarena3** [comment]
fixed in 0.2.0

**Comment by jarena3** [comment]
(sorry, closed erroneously)

**Comment by jarena3** [comment]
resolved in 0.3
