### ISSUE TITLE
Mods that add threat

### ISSUE THREAD

**Issue by TauLupis** [massif-press/cc-lcp-editor#23]
When I try to make a weapon mod that adds threat to melee weapons, it bugs out in compcon. For example, if I set the mod to give Threat 1, then when I equip it on a weapon with Threat 1, it becomes Threat 101. If I set it to give Threat +1, then when I equip it on a weapon with Threat 1 it becomes Threat 10+1.

**To Reproduce**
1. go to add new mod
2. click on added range
3. enter "threat 1"
4. set allowed weapon to "melee
4. save mod to whichever license
5. in Comp/Con, apply mod to a melee weapon
6. the display showing the weapon threat is bugged to show, for example, 101

**Expected behavior**
I would expect it to simply add +N to the threat

**Screenshots**
![Threat](https://user-images.githubusercontent.com/100057877/154827971-f839f75e-6118-4142-ad36-478444faafcf.png)
![mod](https://user-images.githubusercontent.com/100057877/154827972-d9eab78d-fd73-407a-afe2-5ea428a913d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version unsure

**Comment by jarena3** [comment]
resolved in 0.3
