### ISSUE TITLE
Frame Traits, Core Bonuses, cannot have multiple different synergy types.

### ISSUE THREAD

**Issue by Bluhman** [massif-press/cc-lcp-editor#24]
**Describe the bug**
No matter what kind of input is used in the LCP editor, frames and core bonuses cannot seem to have multiple descriptions given for different synergy types. It might extend further than that - the only place I know I've had luck adding multiple Synergy entries to are Mech Systems.

**To Reproduce**
1. Create a new frame for a manufacturer
2. Click on Frame Traits to add a new trait.
3. Scroll down to the Synergies section and add a Synergy to the list.
4. Press the plus button to add a new synergy, add its own details.
5. Press save - The newly saved synergy completely overwrites the old one, despite me pressing the + button.

**Expected behavior**
A new, second block for synergies should be added to the text box next to the first one that was made.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RikerW** [comment]
Fixed in https://github.com/massif-press/cc-lcp-editor/pull/53/commits/94263ccd3b273b21825205cf99b469a5852ae543.
