### ISSUE TITLE
Integers written as Strings

### ISSUE THREAD

**Issue by TheFwuffernaut** [massif-press/cc-lcp-editor#27]
**Describe the bug**
outputting "val" fields and other stats as strings rather than integers, multiple instances of this can be found in compcon-homebrew and sometimes linked in comp-con. Leads to things like Exbats making something Range 35 rather than Range 8. This also effects frames (per post https://discord.com/channels/426286410496999425/679017531033387008/963695910154563626)

**To Reproduce**
1. Make an LCP
2. Add a weapon or frame
3. Input an integer into an integer only field - or at least intended to be integer only - Size, HP, Sensors, Range as examples
4. Finish the rest of the LCP & import to CC proper
5. Add external batteries, level up so your hp increases, anything to modify that integer
6. Because that integer was output as a string you now have range 35

**Expected behavior**
Editor should be able to parse that there's only integers and as such output cleanly without "" around the integer. This should be a simple fix for frames, for weapon range I can understand it may take slightly longer as Mimic Gun for example has a variable range to it - a possible solution for this is to leave a manual override button that just swaps the input of the box to a string.

**Screenshots**
Available in CC homebrew, message links for most recent examples are:
Frame stats - https://discord.com/channels/426286410496999425/679017531033387008/963695910154563626
Weapon stats - https://discord.com/channels/426286410496999425/679017531033387008/964489141322657832

**Desktop (please complete the following information):**
Not desktop related. This is a file output issue that the desktop would have no influence on outside of a keyboard inputting non-integer numbers (stylized in some way)

**Smartphone (please complete the following information):**
I wasn't aware the lcp editor even worked on smartphone? I'm pleasantly surprised if it does but will probably pass on using that format of it.

**Comment by TheFwuffernaut** [comment]
just gonna reply to this so that it gets bumped and maybe seen as it's been a month

**Comment by jarena3** [comment]
resolved in 0.3
