### ISSUE TITLE
[FEATURE] Incorporate License IDs for LicensedItems

### ISSUE THREAD

**Issue by msprijatelj** [massif-press/cc-lcp-editor#28]
**Is your feature request related to a problem? Please describe.**
With version 3.0.44 of lancer-data, `license_id` was added as a field for organizing LicensedItems to avoid collisions between different LCPs (which would presumably use different IDs for their Frames and licenses).  However, this new field is not currently supported by cc-lcp-editor, meaning homebrew creators using the editor will need to add the field in by hand to benefit from the `license_id` filter.

**Describe the solution you'd like**
Alter the Licenses & Equipment editor to include `license_id` as a field, and group licenses together based solely upon whether the license_id matches the frame's regular ID.

**Describe alternatives you've considered**
The above, but tie `license_id` and Frame Name together to keep things easier to track for users (so they're selected as a group, for example).

**Comment by msprijatelj** [comment]
I have a basic script for generating `license_id`s for LicensedItems, but it requires Python 3.8 or higher to run:
https://github.com/msprijatelj/lcp-scripts/blob/main/modify_lcp.py

I may package it up into a `.exe` file with PyInstaller if there's enough demand for it in the meantime.

**Comment by jarena3** [comment]
resolved in 0.3
