### ISSUE TITLE
Mod entries duplicate themselves when editing them.

### ISSUE THREAD

**Issue by Bluhman** [massif-press/cc-lcp-editor#3]
**Describe the bug**
When editing a weapon mod entry and you save, the UI will return to the main license listings and show two copies of the exact same mod entry. Sometimes this also causes changes made to mods to not take. The two entries will still have the same ID listed, but one appears to include the changes made, while the other doesn't (though this might be restricted to only description changes?)

**To Reproduce**
1. Open an existing LCP with mod entries.
2. Open up the Manufacturers & Licenses section and pick a license with a mod.
3. Click on the mod offering.
4. Press the Save button
5. Notice there are now two copies of the exact same mod for the given license.

**Expected behavior**
Editing and re-saving a mod (with the same ID) should just update the information of that mod and not create a superpositional clone of the mod for the license.

**Screenshots**
![image](https://user-images.githubusercontent.com/3156272/139554298-6d0710cb-2ec7-4e72-a8ed-85280d641f81.png)

**Comment by jarena3** [comment]
I'm unable to reproduce this -- I wonder if it was due to the issue in #1 ? If you can still reproduce this issue, could you send me the JSON export?
