### ISSUE TITLE
Variant not Working

### ISSUE THREAD

**Issue by ByteSizedSites** [massif-press/cc-lcp-editor#33]
**Describe the bug**
When you try to create a new frame and make it a variant of an existing frame it doesn't seem to save when you open the frame again in the editor and doesn't show up in comp/con

**To Reproduce**
1. Goto LCP editor home
2. Goto Manufacturers & Licenses
3. Create a Frame
4. Make it a variant of an existing frame
5. Save the frame
6. Open it again
7. There's no variant saved 

**Expected behavior**
Steps 1-6 as above, but the variant remains saved and visible

**Screenshots**
![image](https://user-images.githubusercontent.com/37087248/222056630-e2a2ff49-1fbe-4fa8-8c0b-84af44ea8afe.png)

**Additional context**
Based on opening the exported lcp and converting it to a zip then opening the json is a field "vartiant" and in working jsons it's "variant"

**Comment by ByteSizedSites** [comment]
Also I did manage to solve it, by changing "vartiant" to "variant".
But also deleting the license_id line as it seems to prevent the variant frame from appearing under the proper license.

**Comment by msprijatelj** [comment]
> Also I did manage to solve it, by changing "vartiant" to "variant".
> But also deleting the license_id line as it seems to prevent the variant frame from appearing under the proper license.

@TacoMissile for context, the license_id should match the ID of the Frame whose license you’re trying to add it to. So for Sherman it should be `mf_sherman` iirc.

**Comment by RikerW** [comment]
Fixed at some point, possibly the latest round of variant updates
