### ISSUE TITLE
Auxiliary weapons export as Aux instead of Auxiliary.

### ISSUE THREAD

**Issue by chessisme** [massif-press/cc-lcp-editor#35]
Auxiliary weapons export as Aux instead of Auxiliary. This means that Comp-Con will not use them in the mech editor.

**To Reproduce**
Make and Aux weapon and it will not load.
Change the .lcp extension to .zip and unzip the archive.
Replace all mount:"Aux" with mount:"Auxiliary"
Repack the zip file and make it an lcp.
The Auxiliary weapons now work.

**Comment by chessisme** [comment]
I found the cause.  When a weapon is created it defaults to size "Aux",  it then must be manually changed to "Auxiliary".

**Comment by RikerW** [comment]
Fixed in ce4c22725e7a9dd8e5302c596e41fe8623b2a795 (yes, I know that commit has a name that doesn't match, it was a single line change I snuck in and forgot to mention in the description).
