### ISSUE TITLE
Exported LCPs have empty fields on weapons that cause errors in COMP/CON

### ISSUE THREAD

**Issue by Bluhman** [massif-press/cc-lcp-editor#4]
**Describe the bug**
Any LCPs exported from the editor will include many (if not all?) possible fields of the entry populated with empty strings (""). For some items such as weapons this causes them to throw errors when brought into COMP/CON

**To Reproduce**
1. Create a new LCP with a weapon entry.
2. Fill out basic information for the weapon: enter the information for something like the GMS HMG for example.
3. Export the LCP
4. Import the LCP into COMP/CON
5. View the entry for the new weapon in the COMP/CON compendium.

**Expected behavior**
Either COMP/CON should be updated to handle/ignore empty string entries, or the output of LCPs from the editor should prune any fields that are not populated.

**Screenshots**
Output of LCP Editor from a JSON Export:
![image](https://user-images.githubusercontent.com/3156272/139554955-41c70a1b-55ea-4af7-b9ed-08e3bffc307c.png)

How it shows up in COMP/CON...
![image](https://user-images.githubusercontent.com/3156272/139554937-debebc51-57f6-4a33-a2f1-2e26797dfb2d.png)

If the spare JSON entries on the weapons json are removed, the weapon will show up properly in COMP/CON

**Comment by jarena3** [comment]
Wrote a fix for this one the C/C side. Will close this once that's tested and deployed.

**Comment by jarena3** [comment]
Fixed in C/C
