### ISSUE TITLE
No way to edit/access frame integrated weapons

### ISSUE THREAD

**Issue by Bluhman** [massif-press/cc-lcp-editor#6]
**Describe the bug**
Based on patterns used by base-game LCPs (particularly Sherman and Barbarossa's) Integrated weapons _should list no Source, License Level, or License._ This means they can only validly show up when referenced by the frame that uses the integrated weapon. However, the current LCP editor gives us no way to define an integrated weapon that can match this schema, nor does it allow users to edit weapons that match it either, and also doesn't list the integrated weapons properly for frames that have this setup.

**To Reproduce**
1. Import an LCP copy of the core book data from the [Lancer-Data Repo](https://github.com/massif-press/lancer-data) into the LCP Editor.
2. Open up the licenses section and navigate to the entry for Sherman.
3. Scroll down to its Core System entry.
4. Notice that the Zone-Focus Mk IV SOLIDCORE listing does not have anything in its Integrated Equipment dropdown.
5. Click on the Integrated Equipment drop down - you can scroll down to find the ZF4 SOLIDCORE entry in this list, but it does not appear anywhere else in the LCP Editor

**Expected behavior**
Integrated Equipment entries should work more similarly to how fields like the Deployables section directly to its left do: a list of equipment that can be edited and filled in on its own and directly related to the frame that uses it as integrated equipment.

**Screenshots**
![image](https://user-images.githubusercontent.com/3156272/139555877-e4bae439-9862-4669-99b6-2d69ac0bd625.png)

**Comment by jarena3** [comment]
Managing integrated items like deployables would be a pain to then fit into the lcp structure. Instead I added an empty-source collector for the manufacturer/licenses page, allowing for creation of unlisted integrated items that can then be assigned into integrated/special equipment.
